/-
  tools/probe.lean — the only artifact permitted to decide the verdict.

  WHAT CHANGED, 2026-08-25.  This probe named 49 theorems and tools/run.sh
  passed N=49 to the gate, so the gate went green while ELEVEN theorems in
  PrincipiaVol1.lean had never been asked about:

      epsilon0_of_eq_third_iff · epsilon0_of_two · epsilon0_of_three
      v6_statement_false_at_dimension_five · separation_fails_in_high_dimension
      unfold_stable_branch_is_vacuous · coherent_directions_realise_33
      spectral_trace_ne_33_upto · basin_asymmetry_at_canonical_r_star
      transverse_sum_bound_general · compression_permits_identity

  Those are the V7 additions.  The editorial pass repaired the file and did
  not extend the instrument that checks it, so everything V7 fixed sat
  outside the gate — including epsilon0_of_eq_third_iff, which OPEN_QUESTIONS
  cites as the evidence for O7, and v6_statement_false_at_dimension_five,
  which O1 calls "proved and kept".

  The count check cannot catch this by itself.  It compares the probe's
  output to a number describing the probe.  Calibrating the gate to the
  instrument rather than to the file makes a missing theorem invisible.

  SO DO NOT EDIT THIS FILE BY HAND.  It is generated:

      python3 tools/counts.py --probe

  which reads PrincipiaVol1.lean, emits one line per theorem it finds, and
  prints the N to set in tools/run.sh.  Nothing in that script reads this
  file, so the probe and the number cannot come to agree by copying each
  other -- both are derived from the source.

  A second file, Theorem53NonCommutativity.lean, was briefly added to this
  repo and its seven theorems appended here, taking N to 65.  All seven are
  the same propositions PrincipiaVol1 section 14 already proves, over the
  same intManifold and the same operator instances -- so 65 counted 58
  theorems, seven of them twice.  The file is gone and the duplicates with
  it.  Its theorems are checked here under their PrincipiaVol1 names.
-/
import PrincipiaVol1

#print axioms PrincipiaVol1.V_critical_at_one
#print axioms PrincipiaVol1.V_second_deriv_at_one
#print axioms PrincipiaVol1.V_second_deriv_ne_zero
#print axioms PrincipiaVol1.V_at_one
#print axioms PrincipiaVol1.V_factored
#print axioms PrincipiaVol1.contactCoeff_neg
#print axioms PrincipiaVol1.contactCoeff_ne_zero
#print axioms PrincipiaVol1.gronwall_radius
#print axioms PrincipiaVol1.epsilon0_of_two
#print axioms PrincipiaVol1.epsilon0_of_three
#print axioms PrincipiaVol1.epsilon0_of_eq_third_iff
#print axioms PrincipiaVol1.gronwall_radius_pos
#print axioms PrincipiaVol1.gronwall_radius_lt_one
#print axioms PrincipiaVol1.basin_asymmetry
#print axioms PrincipiaVol1.basin_asymmetry_at_canonical_r_star
#print axioms PrincipiaVol1.mu_canonical
#print axioms PrincipiaVol1.mu_dm3_neg
#print axioms PrincipiaVol1.Phi_pos
#print axioms PrincipiaVol1.dPhi_pos
#print axioms PrincipiaVol1.dPhi_at_threshold
#print axioms PrincipiaVol1.noiseTolerance
#print axioms PrincipiaVol1.gronwall_contraction_below_stability_radius
#print axioms PrincipiaVol1.exp_neg_two_le
#print axioms PrincipiaVol1.exp_neg_twelve_le
#print axioms PrincipiaVol1.transverse_sum_bound
#print axioms PrincipiaVol1.spectral_trace_ne_33
#print axioms PrincipiaVol1.separation_theorem
#print axioms PrincipiaVol1.separation_trace_first
#print axioms PrincipiaVol1.coherent_directions_realise_33
#print axioms PrincipiaVol1.transverse_sum_bound_general
#print axioms PrincipiaVol1.spectral_trace_ne_33_upto
#print axioms PrincipiaVol1.separation_fails_in_high_dimension
#print axioms PrincipiaVol1.dm3_hypothesis_nonvacuous
#print axioms PrincipiaVol1.v6_separation_statement_is_false
#print axioms PrincipiaVol1.v6_statement_false_at_dimension_five
#print axioms PrincipiaVol1.sup_strictMono_isLimit
#print axioms PrincipiaVol1.closurePoints_unbounded
#print axioms PrincipiaVol1.sup_lt_of_regular
#print axioms PrincipiaVol1.closurePoints_stationary
#print axioms PrincipiaVol1.nextLevel_layer_count_gt
#print axioms PrincipiaVol1.regeneration_unbounded
#print axioms PrincipiaVol1.ordinalNextLevel_is_closure_point
#print axioms PrincipiaVol1.ordinal_regeneration_unbounded
#print axioms PrincipiaVol1.regeneration_hierarchy_mahlo
#print axioms PrincipiaVol1.crystal_aspect_ratio
#print axioms PrincipiaVol1.aspect_ratio_encodes_invariants
#print axioms PrincipiaVol1.unfold_stable_branch_is_vacuous
#print axioms PrincipiaVol1.foldMap_not_odd
#print axioms PrincipiaVol1.foldMap_branch_subset
#print axioms PrincipiaVol1.foldSym_branch_subset
#print axioms PrincipiaVol1.shrinkMap_sq_le
#print axioms PrincipiaVol1.nonCommutativity_instance
#print axioms PrincipiaVol1.nonCommutativity_nondegenerate
#print axioms PrincipiaVol1.commuting_instance
#print axioms PrincipiaVol1.compression_permits_identity
#print axioms PrincipiaVol1.exists_order_dependent
#print axioms PrincipiaVol1.not_forall_order_dependent
#print axioms PrincipiaVol1.thm_5_3_is_exactly_existential
