import Vol1.PrincipiaVol1
#print axioms PrincipiaVol1.V_critical_at_one
#print axioms PrincipiaVol1.V_second_deriv_at_one
#print axioms PrincipiaVol1.V_second_deriv_ne_zero
#print axioms PrincipiaVol1.V_at_one
#print axioms PrincipiaVol1.V_factored
#print axioms PrincipiaVol1.contactCoeff_neg
#print axioms PrincipiaVol1.contactCoeff_ne_zero
#print axioms PrincipiaVol1.gronwall_radius
#print axioms PrincipiaVol1.gronwall_radius_pos
#print axioms PrincipiaVol1.gronwall_radius_lt_one
#print axioms PrincipiaVol1.basin_asymmetry
#print axioms PrincipiaVol1.mu_canonical
#print axioms PrincipiaVol1.mu_dm3_neg
#print axioms PrincipiaVol1.Phi_pos
#print axioms PrincipiaVol1.dPhi_pos
#print axioms PrincipiaVol1.dPhi_at_threshold
#print axioms PrincipiaVol1.noiseTolerance
#print axioms PrincipiaVol1.gronwall_contraction_below_stability_radius
#print axioms PrincipiaVol1.exp_neg_two_le
#print axioms PrincipiaVol1.exp_neg_twelve_le
#print axioms PrincipiaVol1.transverse_sum_bound
#print axioms PrincipiaVol1.spectral_trace_ne_33
#print axioms PrincipiaVol1.separation_theorem
#print axioms PrincipiaVol1.separation_trace_first
#print axioms PrincipiaVol1.separation_sharp_at_33
#print axioms PrincipiaVol1.dm3_hypothesis_nonvacuous
#print axioms PrincipiaVol1.v6_separation_statement_is_false
#print axioms PrincipiaVol1.sup_strictMono_isLimit
#print axioms PrincipiaVol1.closurePoints_unbounded
#print axioms PrincipiaVol1.sup_lt_of_regular
#print axioms PrincipiaVol1.closurePoints_stationary
#print axioms PrincipiaVol1.nextLevel_layer_count_gt
#print axioms PrincipiaVol1.regeneration_unbounded
#print axioms PrincipiaVol1.ordinalNextLevel_is_closure_point
#print axioms PrincipiaVol1.ordinal_regeneration_unbounded
#print axioms PrincipiaVol1.regeneration_hierarchy_mahlo
#print axioms PrincipiaVol1.crystal_aspect_ratio
#print axioms PrincipiaVol1.aspect_ratio_encodes_invariants
#print axioms PrincipiaVol1.g6_equals_schumann
#print axioms PrincipiaVol1.foldMap_not_odd
#print axioms PrincipiaVol1.foldMap_branch_subset
#print axioms PrincipiaVol1.foldSym_branch_subset
#print axioms PrincipiaVol1.shrinkMap_sq_le
#print axioms PrincipiaVol1.nonCommutativity_instance
#print axioms PrincipiaVol1.nonCommutativity_nondegenerate
#print axioms PrincipiaVol1.commuting_instance
#print axioms PrincipiaVol1.exists_order_dependent
#print axioms PrincipiaVol1.not_forall_order_dependent
#print axioms PrincipiaVol1.thm_5_3_is_exactly_existential
